In [3]:
import numpy as np
def van(l1):
    mat=np.ones((len(l1),len(l1)))
    for i in range(len(l1)):
        for j in range(len(l1)):
            mat[i][j]=mat[i][j]*(l1[i]**j)
    return mat
lst=[1,2,3]
print(van(lst))

[[1. 1. 1.]
 [1. 2. 4.]
 [1. 3. 9.]]


In [10]:
def mov_avg(a,k):
    l=[]
    count=k
    for i in range(0,(len(a)-k+1)):
        l.append(np.average(a[i:i+k+1]))
    return l
arr=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
#arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(len(arr))
window=3
print(mov_avg(arr,window))

10
[30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 85.0]
